### ISSUE TITLE
PopUp Window - **Phone**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#10]
- [x] The windows name should be "Phone numbers"
- [x] The ID must be the same ID Number in the Debtor Information box on the parent view. This field is the key filter to identify the records corresponding to this Debtor. In the App_Phones, this field is App_Phones_DebtorID
- [x] The NAME field  must be the same NAME  in the Debtor Information box on the parent view. refer to that task to know how to retrieve that piece of information, it is stored in App_Clients
- [x] Change the column names and order to this: Number | Ext. | Type | Confirmed | Status | Reg. By | Date

**Fields Relation**

- [x] Number -> App_Phones_PhoneNumber
- [x] Ext. -> App_Phones_Ext
- [x] Type -> App_Phones_PhoneType
- [x] Confirmed -> App_Phones_Confirmed
- [x] Status -> App_Phones_PhoneStatus
- [x] Reg. By -> App_Phones_CreatedBy
- [x] Date -> App_Phones_CreatedOn

- [x] The records are coming from App_phones and filtered by   `App_Credits_DebtorId <--> App_Phones_DebtorID`

- [x] Activate the option to add a new number, right now the button `+ Add New Number` is not working.
- [x] As part of the previous task, create an add form for this purpose.

- [x] Make Go Back works or remove it cause you have the X at the top right

**Comment by Dhirenvaghani** [comment]
1)  There is No field called  Ext. -> App_Phones_Ext in the App_Phone table,Confirmed ->    App_Phones_Confirmed, Date -> App_Phones_CreatedOn.
2)There is No connection of App_Phone_Status with App_Aux For active and Deactive

**Comment by jalvaradoec** [comment]
**Updated and available:**
No field called Ext. -> App_Phones_Ext
Confirmed -> App_Phones_Confirmed
Date -> App_Phones_CreatedOn

**Clarification**
These fields are booleans and w can handle them as checkboxes for active, inactive.
App_Phone_Status

**Comment by Dhirenvaghani** [comment]
No field called Ext. -> App_Phones_Ext
Confirmed -> App_Phones_Confirmed
Date -> App_Phones_CreatedOn
Can you please provide the value in the tables please

**Comment by jalvaradoec** [comment]
The column linking is all right.
