### ISSUE TITLE
PopUp Window - **Address**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#11]
- [x] The windows name should be "Addresses"
- [x] The ID must be the same ID Number in the Debtor Information box on the parent view. This field is the key filter to identify the records corresponding to this Debtor. In the App_Phones, this field is App_Phones_DebtorID
- [x] The NAME field  must be the same NAME  in the Debtor Information box on the parent view. refer to that task to know how to retrieve that piece of information, it is stored in App_Clients
- [x] Change the column names and order to this: Address | Type | Confirmed | Status | Reg. By | Date

**Fields Relation**

- [x] Address -> App_Addresses_MainStreet
- [x] Type -> App_Addresses_AddressType
- [x] Confirmed -> App_Addresses_Confirmed
- [x] Status -> App_Addresses_Status
- [x] Reg. By -> App_Addresses_CreatedBy
- [x] Date -> App_Addresses_CreatedOn

- [x] The records are coming from App_Addresses and filtered by   `App_Credits_DebtorId <--> App_Addresses_DebtorID`

- [x] Activate the option to add a new number, right now the button `+ Add New Address` is not working.
- [x] As part of the previous task, create an add form for this purpose.

- [x] Make Go Back works or remove it cause you have the X at the top right

**Comment by Dhirenvaghani** [comment]
App_Addresses_AddressType,App_Addresses_Status there is no value for this field in the App_Aux table

**Comment by Dhirenvaghani** [comment]
As you just updated the value in the database now this issue is solved.

**Comment by jalvaradoec** [comment]
Address Status might be just a checkbox... for active/inactive.

**Comment by jalvaradoec** [comment]
The windows columns seems to be all right.
