### ISSUE TITLE
PopUp Window - **Amortization**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#12]
- [x] The windows name should be "Tabla de amortizacion"
- [x] The CEDULA/RUC must be the same ID Number in the Debtor Information box on the parent view. 
- [x] The NAME field  must be the same NAME  in the Debtor Information box on the parent view. refer to that task to know how to retrieve that piece of information, it is stored in App_Clients
- [x] The Operation number must be the same shown at the time in the Operation Details box. Thi field is the key filter to identify the records corresponding to this Operation.  In the App_Amortizations, this field is App_Amortization_BankOperation

- [x] The records are coming from App_Amortization and filtered by   `App_Credits_BankOperNumber <--> App_Amortization_BankOperation`

- [x] Make Go Back works or remove it cause you have the X at the top right

## New Comments to this Pop-Up

- [x] Operation: This is the number read from the Operation Details box and the `filter to apply in App_Amortization_BankOperation to identify the corresponding records.`

- [x] Cuota: This is the share number, as this is debts, the debt is divided into shares. `This information comes from App_Amortization_Share and is also sorted by it.`

As there is no other action or possible combination, I will just describe wich field correspond to each table column after share. Here you can also see better name columns for it.

- [x] Capital <-> App_Amortization_Capital
- [x] Interest <-> App_Amortization_Interest
- [x] ammount <-> App_Amortization_Fee
- [x] Financial Interest <-> App_Amortization_FinInterest
- [x] Mora <-> App_Amortization_DefaultFee
- [x] Expenses <-> App_Amortization_CollectExpenses
- [x] Total <-> App_Amortization_ShareTotal
- [x] Due Date <-> App_Amortization_DueDate

I think we are using too much space in the header of this popup with the debtor information. Can we make it smaller?

**Comment by Dhirenvaghani** [comment]
In amortization table some details need from your side to get the data for the table

**Comment by Dhirenvaghani** [comment]
Please take a look at this task.

**Comment by jalvaradoec** [comment]
Looks Good... just a wrong date format on the last column. please fix.

**Comment by Dhirenvaghani** [comment]
Data in the date field is incorrect

**Comment by jalvaradoec** [comment]
All right, confirmed about incorrect data.
