### ISSUE TITLE
PopUp New Phone Number records

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#14]
- [x] The NUMBER field should be mandatory. Include a red asterisk to denote this property.
- [x] The EXTENSION must be optional.
- [x] The TYPE field must be a drop-down menu, the App_Aux_field must be filtered to "PhoneType" 
- [x] The TYPE should be optional to
- [x] The DATE is not selectable, must use the timestamp, in fact this might be invisible. In the database is configured to use CURRENT_TIMESTAMP function.
- [x] The STATUS checkbox must be activated by default. This way every new phone record is an active record until the user set it the other way.

**Comment by Dhirenvaghani** [comment]
This task is done please take a look at it.

**Comment by jalvaradoec** [comment]
I can't edit records... can we do that clicking directly on the phone number?

**Comment by Dhirenvaghani** [comment]
The Edit Function is done

**Comment by jalvaradoec** [comment]
Looks Good
