### ISSUE TITLE
PopUp New Address record

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#16]
- [x] The ADRESS field should be mandatory. Include a red asterisk to denote this property.
- [x] The TYPE field must be a drop-down menu, the App_Aux_field must be filtered to "AddressType" 
- [x] The TYPE should be optional to
- [x] The DATE is not selectable, must use the timestamp. In fact, this might be invisible. In the database is configured to use CURRENT_TIMESTAMP function.
- [x] The STATUS checkbox must be activated by default. This way every new address record is an active record until the user set it the other way.

**Comment by Dhirenvaghani** [comment]
This task is done please take look on it

**Comment by jalvaradoec** [comment]
I can't edit records... can we do that clicking directly on the address?

**Comment by Dhirenvaghani** [comment]
I have done this Edit changes you can refer it.

**Comment by jalvaradoec** [comment]
Looks good.
