### ISSUE TITLE
Operations Sum is not working fine.

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#17]
I change some records to in the DB to include more operations to the sample Debtor. The result is that the summary of values of each column is not correct. 

**Fix:**

- [x] The CAPITAL column total. looks like it's reading just the first record.
- [x] The INTEREST column total. Looks like it's reading just the first record.
- [x] The PAYMENTS column total. Looks like it's reading the values like text or something like that.
- [x] The DEBT column total.  Looks like its reading just the first record.

**Comment by Dhirenvaghani** [comment]
Please Review this and its done

**Comment by jalvaradoec** [comment]
Works perfectly. thnx
