### ISSUE TITLE
PopUp Window - **Registered Contacts**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#18]
This Popup must show all the related record of registered contacts on the DB.
The source for this the table App_Contacts

### Fields Available for each record

- [x] **Debtor ID Number:** This is the Debtor ID number and is reference and filter to show the correct records, corresponding to this debtor. `When Add a new record, this one should be automatically filled, not asked the user.`

- [x] **ID Number:** This is the ID number of the person referenced in the DB as a contact for this debtor. `When Add a new record, this field is not mandatory and the user can input the data manually. No default value set.`

- [x] **Full Name:** This is the full name of the person referenced as a contact for this debtor. `When Add a new record, this field IS MANATORY, should be marked with a red asterisk and the user can input the data manually. No default value set.`

- [x] **Relation:** This field is to establish the relation between the contact and the debtor. `When Add a new record, this field is not mandatory and the user can SELECT from a drop-down the correct value. The values are stored in App_Aux and you use the following filter App_Aux_field="RefferenceType". No default value set.`

- [x] **Phones:** This will reutilize the Phones popup alredy created for the main window but relating to the ID Numer App_Contacts_RefId

- [x] **Addresses:** This will reutilize the Addresses popup alredy created for the main window but relating to the ID Numer App_Contacts_RefId

- [x] **Created By:** This field is not selectable, must use the timestamp, in fact, this might be invisible as you should take the current user for this.

- [x] **Created On:** This field is not selectable, must use the timestamp, in fact, this might be invisible. In the database is configured to use CURRENT_TIMESTAMP function.

### Aditional tasks here

- [X] Create table and dummy data accordingly to run tests here.

- [x] As part of the previous task, create an add form for this purpose and keep in mind all the previous details about fields functionality.

**Comment by jalvaradoec** [comment]
Ok, the DB is updated.

**Comment by Dhirenvaghani** [comment]
For the Phone number and Adress there aare many fields missing such as for the phone number we  need
1)EXT
2)Type
3)Confirm
4)Status in the App_Contact Table

Similarly we need for the address
I have Added two fields in App_contact for the Phone and Address to continue my work.field name is as follow 
 App_Contacts_PhoneNumber
 App_Contacts_Address

**Comment by jalvaradoec** [comment]
Dilip, I think is in part my mistake not to clarify this on each line. As per we talk that day, the relational field is the debtorID...hens we can use without problems the same tables we are using to store phones and addresses of the debtors, to store the phone and addresses for the contacts. That was the idea on reuse the windows and queries you alredy have in place.

**Comment by jalvaradoec** [comment]
Something is Wrong here. 

The table APP_CONTACTS does not contain any record for this DEBTORID but it still counts 2 records and show them as if there are correct. We have to take a look on how to handle this exception, when the result of the search is NULL.

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
This is ready.
