### ISSUE TITLE
Relation between Operations & Operation Details.

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#19]
Now, we have both boxes right... the next step is when you click on the operation number of the Operation Box, the details in Operation Details must get updated according to the selection.

Some of them come from the DB, other calculated on the fly.

**Comment by Dhirenvaghani** [comment]
Please take a look at it

**Comment by jalvaradoec** [comment]
Looks good for now... i will open new tasks later when i get other pices of information.
