### ISSUE TITLE
Index is not reading correctly the security levels.

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#2]
The index.php file use a **Sesion_Start()** Function to check if there is an open session, but it is not assigning correctly the destination path for each profile.

Must use the same code used in the login page:

`if($_SESSION["logged_in_user"]["App_Users_SecurityLevel"] >= 9)
    {
      $page = "sup_dashboard.php";
    }
    else if($_SESSION["logged_in_user"]["App_Users_SecurityLevel"] >= 5)
    {
      $page = "sup_dashboard.php";
    }
    else if($_SESSION["logged_in_user"]["App_Users_SecurityLevel"] >= 1)
    {
      $page = "oper_dashboard.php";
    }`

This is to assign destination pages in the following way:

- >=9 sup_dashboard.php
- >=5 sup_dashboard.php
- >=1 oper_dashboard.php

I need it this way becasue in the near future we will need to include an administrator dashboard and other funtions that require diferenciation.

**Comment by jalvaradoec** [comment]
Dilip, originally, the index.php file had only 2 alternatives. Send you back to the login page or send you to the supervisor dashboard. 

As we already include user level verification this causes a problem in some cases for the regular operator. When they are logged in and open a new window, the index.php try to send them to the supervisor dashboard and then sent back to the login page when this is not necessary.

We need to modify the index.php to read correctly the user level of the PHP session and then send the user to the proper dashboard. The example is already on this queue so you can get it easily spot.

**Comment by Dhirenvaghani** [comment]
This task done

**Comment by jalvaradoec** [comment]
This is ready.
