### ISSUE TITLE
PopUp Window - **Activitie**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#20]
The objective of this Pop-up is both, to create and edit activities for each Debtor.
As it might be the case where one debtor has more than one debt, there is no sense to include the OPERATION NUMBER in any way in this records. Here are my comments on this Pop-up.

### Design and Relational Notes

- [x] Take out the Operation number... it is not necessary here.

- [x] At the top right, the information on the created by user and date and time of creation, should be smaller, in gray and the date and time in the same line. The idea is to use as little of the pop-up as possible.

- [x] The vertical line separating the top left area and the top right area should be moved to the right to give more space to the client information.

- [x] It feels like it is too much space between the lines in the top boxes. It is using big font size so that much space is not needed. Please narrow it down.

- [x] **TYPE:** This field is intended to declare what type of activities was realized by the operator and should be a dropdown. `When Add a new record, this field IS MANDATORY and the user can SELECT from a drop-down the correct value. The values are stored in App_Aux and you use the following filter App_Aux_field="TaskType". No default value set.`

- [x] **DATE:** Or DUE DATE is the stored day for this activity. When it will be executed. `When Add a new record, this field IS MANDATORY and the user can SELECT from a Calendar Control the correct value. The default control value should be the current date. No default value set on the DB.`

- [x] `TIME:` Although the current form in which the time is settled on the form respond to my original design, it looks awful. I don't know what type of control do we have available to set time in HH:MM format. Please check it out and select what its best based on your experience and criteria. `When Add a new record, this field IS MANDATORY and the user can SELECT from a (You will set this) Control the correct value. The default control value should be the current time. No default value set on the DB.`

- [x] Remember that at the end, this 2 fields DATE and TIME will be merged to be stored in a single column in the database App_Task_DueDateTime 

- [x] **STATUS:** I think the status is very clear. In this specific case means if the activity was realized or not. `When Add a new record, this field is not mandatory`

- [x] **TASK:** This field is where the task description will be stored. `When Add a new record, this field IS MANDATORY`

There is one missing field on the pop-up and that's the outcome.

- [x] **OUTCOME:** This field is where the task outcome will be stored. `When Add a new record, this field is not mandatory`

There is a chance to make a small change or addition here, I will talk with you in the morning to clarify and make a decision about this. 

<img width="479" alt="activities" src="https://cloud.githubusercontent.com/assets/18494618/14701920/5c6363da-076d-11e6-9a12-6f358b90b034.png">

<img width="608" alt="activitie now" src="https://cloud.githubusercontent.com/assets/18494618/14702132/719d3cfc-076e-11e6-821a-6e93504574ab.png">

- The idea is that we use this same pop-up to both, create and edit tasks. If this is possible.

- The reason to autofill date and time instead of use TIMESTAMP in the DB is because this way we make the process a litle bit faster for the users. This window is used create future events AND to register current events. With the autofill the user should just type the task and the outcome and evrything else should be alredy filled out for him, saving time.

- Once the new task is aded or updated, the activities table shoulde be reloaded.

**Comment by Dhirenvaghani** [comment]
Can you please take a look at this task .

**Comment by jalvaradoec** [comment]
Please, can we filter the task list to tasks related only to this profile... 

This should be based on the following condition

`WHERE App_Task_DebtorID = App_Credits_DebtorId`

Plese let me know if need clarification.

**Comment by jalvaradoec** [comment]
Will close this one cause we have another task with the new requirements
