### ISSUE TITLE
PopUp Window - **New Agreement**

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#21]
Hi Dilip, I'm sorry but the last few days has been weird because the replicas and all the stuff we have to do and run because of the past earthquake. It is not an excuse but the effective result is that I have not been able to send yo information needed to keep you focused on the important tasks. 

Now, we have to work in the operational part of this project. The following screen (popup inside operation.php) will be opened when you click the NEW PAYMENT button and the objective is to set up the agreement and once it is settled in the screen, saved and will create all the related transactions based on the provided information. 

Please take a look to the following screen and I will go through each field and how it works.

![oper_newagreement](https://cloud.githubusercontent.com/assets/18494618/14759360/631c11e8-08e6-11e6-9641-77757e40659b.png)

#### Skiped
I will skip all the header fields because I think you already master them. Those fields are: App_Agreement_AgreementID, App_Agreement_OpearationID, App_Agreement_CreatedBy, App_Agreement_CreatedOn

#### Header

- [x] **Agreement Status:** This is to set what's the current status of the Agreement, this will change over the time and the interaction between status and actions will be discussed later. now lets focus on getting the form ready. `The options for this field comes from App_Aux filtering App_Aux_field = "AgreementStatus"` the DB field is `App_Agreement_Status`

#### Variable Fields

- [x] **Cur. Debt.:** The current debt is whatever is settled as Current Debt in the main window and is a read-only field.  <img width="407" alt="current debt" src="https://cloud.githubusercontent.com/assets/18494618/14759407/071d4068-08e8-11e6-8c58-b1d4a64099f6.png">. `The information for this field should be calculated in the same way of the main screen or reading the same variable because it is not stored anywhere.` the DB field is `App_Agreement_InitialDebt`

- [x] **Discount:** Discount is a manual, discount field to be forgiven to the debtor. The default amount for this field is the same as Collection Fees in the main screen, so the operator can ij fact forgive that ammount, or a little more, or even 0 if he wants. `If 0 is the value, then store 0 on the DB and not NULL`  the DB field is `App_Agreement_Discounts`

- [x] **Balance:** The (First) balance field is `Cur. Debt - Discount` and is read only... self calculated. THIS ONE HAVE NO FIELD ON DB, JUST A SCREEN CALCULATION.

- [x] **Downpayment:** This is a manualy entered field with the downpayment ammount.    the DB field is `App_Agreement_DownPayment`

- [x] **Balance:** This New Balance (Second) is the `debt amount - the downpayment.` It is self-calculated.     the DB field is `App_Agreement_Balance`

- [x] **Interest:** This is also self calculated with the following formula `(((NEW BALANCE * 0.18) / 360) *30) * TotalShare#s` With this formula we calculate a year of interests on the new balance, then we calculate the average monthly interest and multyply it with the number of shares for this agreement.   the DB field is `App_Agreement_Interest`

- [x] **# of Payments:** This field dont have a title and is in the middle of the yellow box text. This is the shares you use to calculate the interest in teh previous item.    the DB field is `App_Agreement_Shares`

- [x] **Monthly ammount:**  This is again a calculatd field using the following formula. (NEW_BALANCE+INTERESTS) / #_of_Payments. In this field m we dont want to have decimal or even uneven numbers... so the idea is to usea a formula to round the numbers as much as possible. here some examples: 167,98 -> 170,00  |   202,12 -> 205,00   |    74,01 -> 75.00       Using this aproach you will always have a small remain at the end of the operation and i create a las line to handle it.    the DB field is `App_Agreement_ShareAmount`

- [x] **Last Payment amount:** This is the difference between Grand Total (NewBalance+interests) and the sum of all the previous payments. This one stores the small difference as a last payment.     the DB field is `App_Agreement_LastShareAmmount`

- [x] **Starting On:** This is the date of the first payment, in this case will be downpayment. the DB field is `App_Agreement_StartingOn`

- [x] **App_Agreement_Total:** This is not shown in the screen (by now) but it is stored just to use it in future reports and calculations if needed. it is calculated: `App_Agreement_DownPayment + App_Agreement_Balance + App_Agreement_Interest`

Im going to go for now, i will be on line tmorrow mornig to discuss anything you may need. Thnx.

If you have any questions, please sned them as chat or new comments and keep going with this task, only this task, because this way i will be able to review it sooner and get it working faster. Thnx.

**Comment by Dhirenvaghani** [comment]
On this task I am confused with the three fields i.e 1)# of Payments 2)Monthly ammount: 3)Last Payment amount: can you please clarify more about this i will take a look on monday till then bye.

**Comment by jalvaradoec** [comment]
Hello, Dilip. 

First of all... this is an illustration of which fields are manually entered or edited. 

<img width="880" alt="numerado" src="https://cloud.githubusercontent.com/assets/18494618/14765823/348326cc-09b9-11e6-8291-6f351f6e9035.png">

All the fields without numbers ar calculated fields. no need to edit.


1.-) # of Payments is how many payments (shares) will be this agreement. based on this we can calculate interests.

2.-) Monthly amount is what is the amount the client will pay monthly... the catch here is I want it to be calculated in multiples of 5. If you do this, the majority of the agreements will not match the exact total amount. for example, if a client has to pay 1003,49... the system should and you type 11 payments... the calculation should be 10 payments of 100 and one last payment of 3,49 or something like that. I put an example in the following excel file. 

3.-) Last payment is what I just explain before. Just to manage the small differences.

If you want to, you may use another method to calculate this Rounding numbers I suggest. Just let me know.

Now, for a better understanding of how this works. I'm including an excel file with the information and non-code formulas on how to use them

[Example.xlsx](https://github.com/jalvaradoec/Poligresa-3.0/files/233313/Example.xlsx)

**Comment by jalvaradoec** [comment]
As we discuss, 

- [ ]  Update the Downpayment to the other downpayment field inside the yellow box.

- [ ] The MonthPayment field must be calculated in the line 2175 adding +1  example `var monthpayment=((total)/($('.shares').val() + 1));`

- [ ] ALSO Monthly payments must round numbers and fix them to the nearest higher multiple of 5. examples: 100, 105, 110, 115, 120, 125, 130, 135.  No values in between. 

This last item applies ONLY to MonthPayments and NOT TO LastPayment

**Comment by jalvaradoec** [comment]
I update the table APP_AGREEMENT and convert the following fields to decimal(12,2)

App_Agreement_Balance
App_Agreement_Interest
App_Agreement_LastShareAmmount

**Comment by jalvaradoec** [comment]
Please... review that all the fields get to decimal with 2 decimals. specially the downpayment field. if i write 122.6 it should update to 122.60. This only if is easy and fast. if not, leave it for later in the project.

**Comment by jalvaradoec** [comment]
This is working Awesome.
