### ISSUE TITLE
Change to link

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#25]
Dilip, help me with this.

<img width="723" alt="oper_dash" src="https://cloud.githubusercontent.com/assets/18494618/14823657/e925cad6-0b98-11e6-8cd5-8d280369d9b2.png">

Can you please make the Column OPERATION of this box get every record, linked to the operation.php document using the operation number. This is the parameters you alredy create on it.

http://sistema.poligresa.com/3.0_dev/operation.php?operno=035866320130617000

Thnx

**Comment by jalvaradoec** [comment]
The idea on this one is to remove the ACTION / LINK column from here and to use OPERATION / NUMBER as link. 

- [ ] Remove the ACTION column to save space.

- [ ] Include a DEBTORS NAME column after DEBTORS ID#

- [ ] Remove BANK INTEREST RATE column

- [ ] Also on this same page, remove (BY COMMENTING) the TASKS Box 

- [ ] Make the ASSIGNED OPERATIONS Box full width (keep it at the bottom) to show complete information

Please let me know if you have any question.

**Comment by Dhirenvaghani** [comment]
this task done

**Comment by jalvaradoec** [comment]
Everything checkd.
