### ISSUE TITLE
NEW AGREEMENT CALCULATOR

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#27]
I want to ask you something
remember the screen to calculate payments based on the number of months

![image](https://cloud.githubusercontent.com/assets/18494618/15238667/4ca0ad38-18a0-11e6-90a8-85830cd1c738.png)

well… i need to make a copy of but without the SAVE button
the idea of having 2 of them is that 1 will only be used for calculations
and the other to create the agreement plan

I ask to have them separated beacuse i will ask you in a separated task to block some fields in one of them, hence you will neede separated code for them

thnx

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
Dude, an you put again the BACK button.

I just want to remove the save button, no both of the,

**Comment by jalvaradoec** [comment]
Ok, Great. Thnx
