### ISSUE TITLE
Simplify the ACTIVITY window

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#28]
Dilip, we need to get more focus on the ACTIVITIES of the operator and simplify the windows. Also, we need to make options appears when relevant. 

For now, I need you to make a copy of the code of the Activity window ith all the functionality and mark it as a comment so we can retrieve it from the file itself if necessary in the future.

These are the fields wee need to see on the activity window (related with original software).

![diapositiva2](https://cloud.githubusercontent.com/assets/18494618/16033102/cd4f4d02-31cf-11e6-9b88-51e9575bfe7d.jpg)
![diapositiva3](https://cloud.githubusercontent.com/assets/18494618/16033103/cd570984-31cf-11e6-8b01-a11531ee476a.jpg)
![diapositiva4](https://cloud.githubusercontent.com/assets/18494618/16033104/cd595a86-31cf-11e6-9f86-88c1c26d8ae7.jpg)

Please, remember to copy and comment the original code because we will use it later this week, braking the tasks in something easier.

**Comment by Dhirenvaghani** [comment]
This Task is done

**Comment by jalvaradoec** [comment]
Please, on the first row leave TYPE alone ALIRGNED aligned to the right
Second Row would be RESPUESTA - CONTACTO - TIPO
Third Row, would be COMP/ABONO - FECHA - HORA
then the OUTCOME. Plese change size and location cause it looks weird there, maybe wider and centered.

Remove the DONE checkbox and place the OUTCOME field

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
Forget to remove this section of the form. I told you about this on skype.

![image](https://cloud.githubusercontent.com/assets/18494618/16219896/fb016fb2-374e-11e6-8607-647847600949.png)

Please, remove that part cause it should be on a separated window later when triggered.

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
It works properly.
