### ISSUE TITLE
Change the ACTIVITIE LOG

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#29]
We need to show relevant information on the Activitie log for each loan.

Here is what to change, how it should look like and from where to take the information.

![diapositiva5](https://cloud.githubusercontent.com/assets/18494618/16033278/c83b1336-31d0-11e6-9c52-b5a7d17aacd9.jpg)
![diapositiva6](https://cloud.githubusercontent.com/assets/18494618/16033279/c843c76a-31d0-11e6-8b77-71b7a6df99a9.jpg)

The last image contains the source of the columns, in the right order.

Please, keep in mind that there is no longer an EDIT option on this list. The user must have the ability to open and see the details, but not change it. 

The Supervisor (Level 5 and up I think) can change it, regular users not.

**Comment by Dhirenvaghani** [comment]
can you please late me know which data table i have to used from database

**Comment by jalvaradoec** [comment]
App_activities, just i think there are missing fields. Would you please update the table to include what you need there

**Comment by Dhirenvaghani** [comment]
in App_Logs table there are two field called App_Logs_Conciliated and App_Logs_Effective , from  where i should get data for those fields

**Comment by Dhirenvaghani** [comment]
https://cloud.githubusercontent.com/assets/18494618/16033104/cd595a86-31cf-11e6-9f86-88c1c26d8ae7.jpg
in this screen short field called "hora" where should i map this in  App_Logs table

**Comment by jalvaradoec** [comment]
Thats the TIME for the DATETIME field on the table



Saludos,

Jorge Rene Alvarado V.




2016-06-15 4:27 GMT-05:00 Dhiren <notifications@github.com>:

**Comment by jalvaradoec** [comment]
Conciliated and Effective are there for later. no use right now. 

We will need to use them to store calculated information an reporting.

**Comment by Dhirenvaghani** [comment]
This Task is done

**Comment by jalvaradoec** [comment]
Plase change the format to show only DATE and hide the time. 

Also, I can see that all the records are settled on time 00:00:00. In the form are time fields called HORA. 
Fecha=Date
Hora=Time

The record should store FECHA + HORA 

> 2016-06-16 22:34:19

Please take a loon on this because if you dont do it this way, there is no time record (cause i dont include independent time columns on the database.

Let me know if you have any question,

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
Confirmed.
