### ISSUE TITLE
Contacts counter

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#30]
The Registered contacts section (or the related query on the form) is not showing acurate information.

![image](https://cloud.githubusercontent.com/assets/18494618/16072022/32188940-32a4-11e6-97a7-fa0ab8219460.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16072028/394c901c-32a4-11e6-975d-e4cef84a81a7.png)

Please check this out and fix it.

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
Now it says 2 contacts and have 3. 

I remember that I delete all the contacts for this debtor on purpose to test it WHAT IF.

Plesae check.

**Comment by Dhirenvaghani** [comment]
This task is done

**Comment by jalvaradoec** [comment]
tested and ready.
