### ISSUE TITLE
Add phone numbers to the search results.

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#31]
This will help the operator to get the information of the debtor.

**Comment by jalvaradoec** [comment]
can we do this?

This would be very helpful because the operators receive many calls and they don't know who's calling. Having the ability to search by phone number will help them to identify the debtor and maintain leverage over the phone call.

**Comment by Dhirenvaghani** [comment]
this task done

**Comment by jalvaradoec** [comment]
Somethign is not matching here.. please take a look on the profile information against the search result information

![image](https://cloud.githubusercontent.com/assets/18494618/16254807/82f20912-3809-11e6-8878-ee293cf0fdde.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16254811/8ca938d6-3809-11e6-8061-25fb64639966.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16254820/9ade9dba-3809-11e6-83e5-05ad6f9c8fbf.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16254832/a7bed36a-3809-11e6-96f5-392f2e370342.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16254836/b151bf64-3809-11e6-9697-5ac30b40d222.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16254844/bd7c335a-3809-11e6-92fe-17d64ceb4af9.png)


Debtor Profile:
![image](https://cloud.githubusercontent.com/assets/18494618/16254859/df5d7330-3809-11e6-9d33-3e3056848211.png)


Search result:
![image](https://cloud.githubusercontent.com/assets/18494618/16254852/cbe4d94c-3809-11e6-9b5b-6874a207bf58.png)


- [ ] Please review and fix.

- [ ] Also, I need to know what happen when there are more that 1 phone number registered. we need to searcho across all of them.

**Comment by jalvaradoec** [comment]
![image](https://cloud.githubusercontent.com/assets/18494618/16259672/69cdd4b4-3829-11e6-84a9-4fd6f78aab29.png)

The information repeats itself for each new phone number added. I guess you are sharing the query with search, I suggest to copy it to avoid this problem. O whatever you think will work.

**Comment by Dhirenvaghani** [comment]
This task done

**Comment by jalvaradoec** [comment]
![image](https://cloud.githubusercontent.com/assets/18494618/16293201/847521b4-38dd-11e6-879e-90e2a69ea1f2.png)

Not working fine. But I think I now where is the issue. We are sharing the APP_Phones table to store both, debtors phone numbers AND debtors contacts phone numbers. This is absolutely ok, the issue comes because the first record shown is a debtors contact phone number, and not the Debtors number. This can be solved with a simple change on the relation of the query.

![image](https://cloud.githubusercontent.com/assets/18494618/16293254/0b0e9af2-38de-11e6-9bc5-9a7a9d61ae4e.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16293262/196b4028-38de-11e6-95e4-5da48bc6cd09.png)

**Comment by Dhirenvaghani** [comment]
need to disuse with you

**Comment by Dhirenvaghani** [comment]
this  task done

**Comment by jalvaradoec** [comment]
ready.
