### ISSUE TITLE
Search results link

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#32]
When yo run a search… you get some information on the screen but there is no way to go deeper
We need to include a link to open any record the operators what.
For this matter, I propose to make the OPERATION ID clickable and open the selected record on the OPERATION.PHP page so he can get the full view.

**Comment by Dhirenvaghani** [comment]
this task done

**Comment by jalvaradoec** [comment]
Working fine.
