### ISSUE TITLE
Empty columns

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#33]
There are 3 empty columns on the SEARCH RESULTS, this might be because there was no defined fields for this when it was created.

The Columns are:

- [x] CAPITAL

- [x] INTERESTS

- [x] COLLECTION FEES

- [x] Also, please remove the Time Stamp from the BANK DUE DATE Column

**Comment by Dhirenvaghani** [comment]
this task done

**Comment by jalvaradoec** [comment]
done
