### ISSUE TITLE
Fix for Header App Title

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#35]
![image](https://cloud.githubusercontent.com/assets/18494618/16222855/fc534050-375f-11e6-8448-57181ebe4133.png)

When you click on the POLIGRESA at the top left (intersection between menu and header) it takes you to a wrong page.

It should redirect you to index.php, and index.php will take you to the right page according to your security level.

Another approach to doing this, is to make differential links based on security levels. This second option will take a little bit more coding but it would be the best choice because we avoid one unnecessary redirection.

**Comment by Dhirenvaghani** [comment]
this task done

**Comment by jalvaradoec** [comment]
Fixed directly on menu, this is great.
