### ISSUE TITLE
Filter Phones

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#39]
Hey, the Operation panel must shou only ACTIVE PHONE NUMBERS.
Please change the SQL Query.

![image](https://cloud.githubusercontent.com/assets/18494618/16293329/b29cd6ee-38de-11e6-96aa-5bccd63030f1.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16293334/bb5d8c4c-38de-11e6-861d-c7c0e62425c5.png)

![image](https://cloud.githubusercontent.com/assets/18494618/16293346/d29d5054-38de-11e6-824f-fb33d67b293a.png)

-------------------

![image](https://cloud.githubusercontent.com/assets/18494618/16293352/daaa5e68-38de-11e6-960e-b3bb1a160239.png)

------------------------

Only when status is Active.

**Comment by Dhirenvaghani** [comment]
This Task done

**Comment by jalvaradoec** [comment]
it works
