### ISSUE TITLE
Dbtr Grl Info Box - Relation Fields / Tables

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#5]
FIELD   --->   table.field

- [x] ID --> App_Credits_DebtorId + " / " App_Clients_FullName (where: `App_Credits_DebtorId = App_Clients_DebtorIdNumber`)

- [x] PHONE --> App_Phones_PhoneNumber (Where: `App_Credits_DebtorId =App_Phones_DebtorID AND App_Phones_PhoneStatus = 1` count to the 2 or 3 first records)

- [x] ADDRESS --> App_Addresses_MainStreet (where: `App_Credits_DebtorId = App_Addresses_DebtorID AND App_Addresses_Status = 1`)

- [x] Change the text ZONE for City

- [x] City (previously Plaza): App_Aux_text (where: `App_Aux_field = "City" AND App_Aux_value = App_Clients_City`)

- [x] Route: App_Aux_text (where: `App_Aux_field = "Route" AND App_Aux_value = App_Clients_BankAgency`)

**Comment by Dhirenvaghani** [comment]
This is done Please Make a review and Close this task

**Comment by jalvaradoec** [comment]
- [ ] Normalize header

- [ ] Change Zone for City

- [ ] Fix Route

- [ ] Bold to all Titles

**Comment by jalvaradoec** [comment]
I think this box is done. I will create separate issues for the popup views.
