### ISSUE TITLE
Operations Box - Relation Fields / Tables 

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#6]
This box is intended to show all the debts registered by this person. Each debt has an Operation number (App_Credits_BankOperNumber) and is related to the Debtor using the Debtors ID Field (App_Credits_DebtorId) which must match the Debtor ID selected in the Debtor General Information Box (App_Clients_DebtorIdNumber)

- [x] Then as it is possible for one person to have more than 1 debt, all the Operations related to that Debtor ID (App_Clients_DebtorIdNumber) must be shown in the table inside this box and give a sum of some of the fields (the numeric fields).
- [x] Remove the column "More" , this was there just to select the displayed operation in the next box Operation Details Box, but we can make it just by creating the same action putting the link in the Operation number (first column of the table). The idea is now to click the operation number to select the showed operation and remove the last column in this table 

**Basic fields relationship**

- [x] Operation -> App_Credits_BankOperNumber 
- [x] Capital -> App_Credits_BankTotalCredit
- [x] Interest -> CALCULATED - Use Capital * 0.18 for now
- [x] Payments -> From View not yet created - Use $500 for now
- [x] Debt -> CALCULATED (Capital + Interest - Payments)
- [x] Product -> App_Credits_BankCreditType LookUp from App_Aux**
- [x] Due Date -> App_Credits_BankDueDate 
- [x] Status -> App_Credits_Status LookUp from App_Aux**

Right now the test cases with more than 1 credit are the following debtors IDs:

1302430523
0909036998
0915815203
0922392691

**Comment by Dhirenvaghani** [comment]
Please Check this and let me know if you have any issue in this.

**Comment by jalvaradoec** [comment]
- [x] Align headers of the table
- [x] Normalize $ symbol from all the numbers and values.
- [ ] All the values must be fixed to 2 decimal digits even if they are fixed numbers.
- [x] All the values must be aligned to the right to make the decimal digits match.
- [ ] Due Date must be shown as Date Only

**Comment by Dhirenvaghani** [comment]
The issue You have ask me to verify is done

**Comment by jalvaradoec** [comment]
Ready. thnx.
