### ISSUE TITLE
Activity Box - Relation Fields / Tables

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#7]
The objective of this box is to list all the Activities (Tasks) related to a specific debtor independent of the operation. The idea is to have a list of scheduled activities and at the same time, a registry of previous activities, the relation must be done between `App_Task_DebtorID <-> App_Clients_DebtorIdNumber`

- [x] I would like to filter this list to the newest 30 records. The tasks history for a debtor can get very big quickly and i dont want to fill the screen with obsolete information.

- [x] Before get into the fields relations, i would like to "Merge" Date and time to show this information in a single column using a datetime so use in a better way the available space.

**FIELDS RELATIONS**

- [x] Done -> App_Task_Status, it is showed as a checkbox to know what task is ready and wich one is pending.

- [x] User -> App_Tasks_AssignedTo, it shows who is responsible to excute the task. Search for the userID in the App_Users table and show the Username (App_Users_username)

- [x] Date/Time -> App_Task_DueDateTime

- [x] Type -> App_Task_TaskType, It shows the Task Type looking on the App_Aux table filtering the App_Aux_field = TaskType

- [x] Observations -> App_Task_Description

**Comment by Dhirenvaghani** [comment]
Please Take Look on this and let me know if you have any issue

**Comment by Dhirenvaghani** [comment]
There is no Data in the Table App_Aux for the Field Type.So please Insert the data in the table so we will have the Data on the Activity Box

**Comment by jalvaradoec** [comment]
I guess I forgot to push the DB update with those fields. It is updated and available now.

**Comment by Dhirenvaghani** [comment]
As you fill the value to type filed now it is fine

**Comment by jalvaradoec** [comment]
It looks like this is ready.
