### ISSUE TITLE
Operation Details Box - Relation Fields / Tables

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#8]
The operation details are the same fields showed in the Operations Box in a different layout and adding 
a little bit of additional information.

Before go further to the fields relations, some things must be fixed.

- [x] Align correctly the fields names and the values. Right now they are not all aligned.
- [x] Once this is done, the vertical space should be better distributed. right now it seems like there is some useless space.
- [x] All The values must work with 2 decimal digits.
- [x] All the values must be aligned to the right. This is to make it visually easier to read.
- [x] The (+) and (-) text should be placed in the field text and not in the values to make it easier. 
- [x] But a <BR> after Current Debt to put a space between the last line and the box border.
- [x] Remove the SHOW TABLE link and make this popup shows when you click on the PRODUCT TYPE, in the case of the example it is "Amortization". So, instead of use a separated link, the popup will show when you click on it.

**Fields Relations**

- [x] Capital -> App_Credits_BankTotalCredit
- [x] Interest -> CALCULATED - Use Capital * 0.18 for now
- [x] Initial Debt -> CALCULATED (CAPITAL + INTEREST)
- [x] Previous Payments -> From View not yet created - Use $650 for now
- [x] Debt -> CALCULATED (Capital + Interest - Payments)
- [x] Collection Fees -> CALCULATED - USe Initial DEbt * 0.2 for now
- [x] This Month Payments  -> From View not yet created - Use $150 for now
- [x] Current Debt   -> CALCULATED (Capital + Interest - Payments + Collection Fees - This Month Payments)

**Comment by Dhirenvaghani** [comment]
Please make a review on this page and let me know if you have any issue

**Comment by jalvaradoec** [comment]
Small fix done on a query line 218. now closed
