### ISSUE TITLE
PopUps buttons

### ISSUE THREAD

**Issue by jalvaradoec** [jalvaradoec/Poligresa-3.0#9]
The Go Back buttons int he Popups (all of them) is not workin. Fix it please.

**Comment by Dhirenvaghani** [comment]
please review and let me know if you have any changes

**Comment by jalvaradoec** [comment]
Please check again this items, looks like they are not working right.

- [ ] Go back for `Show Registered Contacts` is not working correctly.
- [ ] Go back for `Amortization table` is not working correctly

**Comment by Dhirenvaghani** [comment]
All the issue are resolve.

**Comment by jalvaradoec** [comment]
Ready :)
